### ISSUE TITLE
 aldex.corr having unexpected behavior

### ISSUE THREAD

**Issue by valscherz** [ggloor/ALDEx_bioc#13]
Hi,

Thanks for the development of this very interesting tool. I am trying to use it for assessing correlation between 16S rRNA microbiota composition and a numeric continuous variable and I am facing issues with the aldex.corr function.

Here are my session infos :

```
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)

Running under: Ubuntu 18.04.2 LTS
Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ALDEx2_1.14.1     ggplot2_3.1.0     phyloseq_1.26.1   readr_1.3.1       tidyr_0.8.2       tibble_2.0.1     
 [7] data.table_1.12.0 dplyr_0.8.0.1     vegan_2.5-4       lattice_0.20-38   permute_0
```
Then following the aldex.corr description from [this manual](https://www.bioconductor.org/packages/devel/bioc/manuals/ALDEx2/man/ALDEx2.pdf), I understand that I must first compute _aldex.clr_ to then feed its output to _aldex.corr_:

```
# Toy values
values <- round(runif(14,1,5), 2)
data(selex)
selex <- selex[1201:1600,]

## Correlation
x <- aldex.clr(selex, values)
```
But here is what I obtain:

> Error in validObject(.Object) :
> invalid class “aldex.clr” object: invalid object for slot "conds" in class "aldex.clr": got class "integer", should be or extend class "character"

Which can be fixed by

```
## Correlation
x <- aldex.clr(selex, as.character(values))
```
**Yet this looks like a bad idea...**

And since I am on it, the following example found in the [manual](https://www.bioconductor.org/packages/devel/bioc/manuals/ALDEx2/man/ALDEx2.pdf) is not working neither, throwing the same error:

```
data(selex)
#subset for efficiency
selex <- selex[1201:1600,]
x <- aldex.clr(selex, 1:14)
corr.test <- aldex.corr(x)
```
> Error in validObject(.Object) :
> invalid class “aldex.clr” object: invalid object for slot "conds" in class "aldex.clr": got class "integer", should be or extend class "character"

Could you provide some guidance here? Thank you!

Valentin

**Comment by ggloor** [comment]
I see what the problem is and I will try and fix it today and push to the developer branch. Thanks for finding this bug.

**Comment by ggloor** [comment]
This problem is fixed, and pushed to the bioconductor developer source. It should be build tonight, but if you want to run this version of ALDEx2 now, do the following. it should build and install fine as there are no new dependencies

1: down the repository and run in the command line >R CMD BUILD ALDEx2_bioc
2: inside R >install.packages("ALDEx2_1.15.4.tar.gz", type="source", repos=NULL)

**Comment by valscherz** [comment]
Good to hear, thank you very much!
