### ISSUE TITLE
Calculation of Geometric Mean

### ISSUE THREAD

**Issue by kenscripts** [ggloor/ALDEx_bioc#15]
Hi,

I am currently using ALDEx2 for my 16S amplicon sequencing studies. I wanted to log2 clr transform my table for graphing purposes so I referred to your clr_function.R code to see how you calculated the geometric mean. I noticed on lines 170, 186, 192 of clr_function.R that only the mean function was used. Not sure if I am reading the code correctly but I thought that the mean function calculates the arithmetic mean and not the geometric mean? 

Best,
Kenny

**Comment by ggloor** [comment]
Dear Kenny
The function is calculating the arithmetic mean of the logarithm of the vector, which is the geometric mean of the non log-transformed data vector

**Comment by kenscripts** [comment]
Thank you! I knew I was missing something.

Best,
Kenny
