### ISSUE TITLE
BiocParallel error in clr_effect.r

### ISSUE THREAD

**Issue by jmmack** [ggloor/ALDEx_bioc#19]
`x.effect <- aldex.effect(x, conds, include.sample.summary=TRUE, verbose=TRUE)`

Error in "BiocParallel" %in% rownames(installed.packages()) & useMC : 
  operations are possible only for numeric, logical or complex types

**Comment by louellette** [comment]
I hit this issue also.  Do I have something misconfigured?  My same code runs fine on my laptop.  I just finished upgrading the server R and installing all the required packages there, so I'm running different versions.  See attached.
[BiocParallel error.txt](https://github.com/ggloor/ALDEx_bioc/files/4308683/BiocParallel.error.txt)

**Comment by ggloor** [comment]
fixed and pushed to the development version. This can be downloaded from the ALDEx_bioc master branch, or from https://www.bioconductor.org/packages/devel/bioc/html/ALDEx2.html. Make sure the version is 1.19.2
