### ISSUE TITLE
aldex.glm with model.matrix

### ISSUE THREAD

**Issue by Maraikep** [ggloor/ALDEx_bioc#23]
Hi Greg,
Thanks for the prompt reply! 
Yes, I was trying via bioconductor. 
I just tried the following:
1) Download as source and install using install.packages(PATH.tar.gz, type = "source). 
Result: "Package unavailable for R3.5.2"
2) Updating R to 4.0. Retry. 
Result: Exits with the same message, but for R4.0.
3) Trying via URL from github: install.packages("ALDEx2", repos = "https://git.bioconductor.org/packages/ALDEx2", type="source")
Result: unable to access index for repository;  package ‘ALDEx2’ is not available (for R version 4.0.0)

Can you help me on how to update, please?
Thanks a lot in advance!
Best,
Maraike

####Former email######
Hello,
First of all, thanks for the nice package ALDEx2. Its a great idea and a very, very useful tool! Thanks!
I am having a problem running what has been called a 'complex design' in this forum. In this regard, I would like to ask two questions:

    Every time I am running the analysis with a model.matrix, I am getting an error message "Error in coerce.data(reads, conds) : mismatch between number of samples and condition vector". To me, they seem to match... (dim()). I also run the example from the vignette - with the same error.
    covariates <- data.frame("A" = sample(0:1, 14, replace = TRUE),
    "B" = c(rep(0, 7), rep(1, 7)))
    mm <- model.matrix(~ A + B, covariates)
    x <- aldex.clr(selex.sub, mm, mc.samples=8, denom="all")
    What am I doing wrong? I would like to get this to work as I will have several factors eventually.
    Can this be a version problem? I am running the analysis with ALDEx2 1.14.1.. I saw, there is ALDEx2 1.20 available. However, it appears, I cannot update and all tries to update the package failed... A colleague said she was using 1.18.0. However, for her it worked only with the model.matrix and her attemps to run the aldex.clr with a character failed.
    Did I understand correctly, that I only have to run a model.matrix approach if I am using more than 1 factor, independent of the number of its levels? In other words: The model.matrix approach is for designs with more than 1 factor variable, is that correct? For only one factor, I can simply run it as 'conds'?!

Thank you very much in advance for your kind help!
Yours faithfully,
Maraike

Answer GGloor: 
Hi Maraike

Yes this is a version problem. You should update to the latest version of aldex that fixes that bug

Are you trying to update through bioconductor?

Please move this question to aldex_bioc

**Comment by ggloor** [comment]
did you try:

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ALDEx2")
