### ISSUE TITLE
Negative num. error when running aldex.effect for alr transformation

### ISSUE THREAD

**Issue by aimirza** [ggloor/ALDEx_bioc#26]
I clr transformed the data using a single index, effectively an all transformation. However, I received two errors:

1. Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing values and NaN's not allowed if 'na.rm' is FALSE

2. Error in if (any(n < 0)) stop("counts cannot be negative") : 
  missing value where TRUE/FALSE needed

I forked the repository and fixed error #1 by adding the parameter `na.rm = TRUE`  to the `quantile `function. I think the NAs is from the reference feature. 

Error #2 is from the script rdirichlet.r. Would there be an issue with the results if I remove the code `if ( any( n < 0 ) ) stop("counts cannot be negative")` from the script? Is there a better way to deal with these errors while using a single index as the denom?

**Comment by ggloor** [comment]
The error was misleading, it was caused by NAs in the output.
the aldex.effect function is now fully compliant with an ALR denominator. 
you can try it by installing from source. I will push it to the development version of bioconductor
