### ISSUE TITLE
Allow cmultRepl from zCompositions and option not to add 0.5 pseudocount 

### ISSUE THREAD

**Issue by aimirza** [ggloor/ALDEx_bioc#28]
Because aldex.clr forces data to be integers it will make the zero replacement by cmultRepl (from zCompositions) ineffective. After using cmultRepl, I have to transform the values to integers (e.g., using ceiling) but then many of the zero replacement become 1 when they were type double. Furthermore, aldex.clr adds a pseudocount of 0.5, thus many of my 0s now have a count of 1.5. It would be great instead of forcing users to input counts to instead output a warning when integers are not used. I understand that users may mistakenly input proportions instead of counts but hopefully, the warning will guide them. It would be great to have an option to use cmultRepl for zero replacement instead of adding 0.5. Thank you for addressing my previous questions!

**Comment by ggloor** [comment]
adding cmultRepl prior to the transformation will defeat the purpose. cmultRepl and then clr transforming is is an extremely biased representation of what was *actually observed in this individual* experiment. The aldex.clr output with a prior of 0.5 is a distribution that represents a distribution of what *could have happened* had you conducted more replicates. They are not directly interconvertible, but if sample sizes are large enough are very similar.

We have tried non-uniform priors, or allowing the user to select a prior and in the end it makes very little difference if the user has sufficient mc.samples (at least 16, 128 or more preferred). So for the sake of simplicity this is preferred.
