### ISSUE TITLE
Aldex clr_function.R bug when using the glm function

### ISSUE THREAD

**Issue by tbrowne5** [ggloor/ALDEx_bioc#29]
Opening a bug report for the ALDEx2 (ALDEx_bioc) GLM function in R 3.5.1. Error:

> R version 3.5.1 (2018-07-02)
> Error in coerce.data(reads, conds) :
>   mismatch between number of samples and condition vector
> Calls: aldex.clr -> aldex.clr -> aldex.clr.function -> coerce.data

The exact code used with R 3.5.1 is:

> data(selex)
> covariates <- data.frame("A" = sample(0:1, 14, replace = TRUE),"B" = c(rep(0, 7), rep(1, 7)))
> mm <- model.matrix(~ A + B, covariates)
> x <- aldex.clr(selex, mm, mc.samples=1, denom="all")

Error location — ALDEx2 clr_function.r:

> if(ncol(reads) != length(conds) & !is(conds, "matrix")){
> print(length(conds))
> print(ncol(reads))
> stop("mismatch between number of samples and condition vector")
> }

**Comment by ggloor** [comment]
fixed. Thx
