### ISSUE TITLE
Option for providing self-computed IQLR or CLR? 

### ISSUE THREAD

**Issue by jolespin** [ggloor/ALDEx_bioc#31]
Your package is highly regarded in the compositional data community and would love to try it out on my dataset.  However, I often use CLR or IQLR for different analysis so I have the dataframes precomputed.  Is there an option to provide a precomputed CLR or IQLR as input?

**Comment by ggloor** [comment]
sorry for the stupidly late response

tldr: not at this point

However, you could put your precomputed values into the aldex.clr@analysisData slot and downstream analyses #might# work

not sure why you would want to do this.

**Comment by jolespin** [comment]
Yea it's definitely not an essential feature request just a thought. The main reason is that I have been trying to make my workflow very modular where I compute something once then use it for multiple analysis instead of recomputing each time. The second reason is more experimental as I've been working with different variations of IQLR that may or may not be more robust than CLR depending on the circumstances.
