### ISSUE TITLE
Installation via Anaconda not working on Mac OS and Linux

### ISSUE THREAD

**Issue by sbslee** [ggloor/ALDEx_bioc#33]
Hello!

Thank you for developing the awesome tool. I'm looking forward to trying out your tool soon.

I currently have an issue when installing ALDEx2 via Anaconda in both Mac OS and Linux. I'm trying to download ALDEx2 from https://anaconda.org/bioconda/bioconductor-aldex2. Here's what I did in Mac OS and Linux:

```
$ conda create -n r_env
$ conda activate r_env
$ conda install -c bioconda bioconductor-aldex2
```

This gives:

```
$ conda install -c bioconda bioconductor-aldex2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                             

UnsatisfiableError: 

$ 
```

I spent the last 48 hours trying to work this out without success. For example:

1. I tried downloading lower versions of ALDEx2 that are available in the bioconda channel (https://anaconda.org/bioconda/bioconductor-aldex2/files). For instance:

```
conda install -c bioconda bioconductor-aldex2=1.14.1
```
But no luck there.

2. I tried installing ALDEx2 via BiocManager after setting up a clean R environment in Anaconda, but no luck there etiher.

At the end, I did eventually manage to install ALDEx2 using the R software that I downloaded from CRAN, not from Anaconda. I can confirm it works fine in this specific context (Mac OS). However, the problem is that I need to run ALDEx2 in my team's server (Linux) and in the Anaconda environment for package management purposes. Therefore, even though I can run some urgent analyses in my local computer, I need a more long-term solution (i.e. installing ALDEx2 via Anaconda).

Could you please look into this? That would be much appreciated.

**Comment by dgiguer** [comment]
Hi @sbslee 

I'm having trouble reproducing the problem, I'm able to install 1.22.0 on mac. Can you post the output from `conda list` in your aldex2 environment?  

Atlernatively, I have found for other packages that creating the environment and installing the package in one step has resolved the "UnsatisfiableError:" issue. This *should* set up an environment that satisfies the dependencies of aldex2. Try:

```
conda create -n aldex2 -c bioconda bioconductor-aldex2
```

Dan

**Comment by ggloor** [comment]
thx

some say i need a conda tutorial.

i’ve been hacking snd have improved the speed of aldex.effect by 50%

actually runs fast rona single core than multi core

gg

From my iPhone

On Dec 5, 2020, at 3:33 PM, Daniel Giguere <notifications@github.com> wrote:

﻿

Hi @sbslee<https://github.com/sbslee>

I'm having trouble reproducing the problem, I'm able to install 1.22.0 on mac. Can you post the output from conda list in your aldex2 environment?

Atlernatively, I have found for other packages that creating the environment and installing the package in one step has resolved the "UnsatisfiableError:" issue. This should set up an environment that satisfies the dependencies of aldex2. Try:

conda create -n aldex2 -c bioconda bioconductor-aldex2


Dan

**Comment by sbslee** [comment]
Hi @dgiguer,

Thank you for the prompt reply! I can show you the result of `conda list` but there is really nothing here because nothing got installed due to `UnsatisfiableError`:

```
(base) [sbslee@grchead ~]$ conda activate r_env
(r_env) [sbslee@grchead ~]$ conda list
# packages in environment at /nfs/home/sbslee/anaconda3/envs/r_env:
#
# Name                    Version                   Build  Channel
(r_env) [sbslee@grchead ~]$
```

I tried your suggestion, but I'm getting the same error:

```
(base) [sbslee@grchead ~]$ conda create -n aldex2 -c bioconda bioconductor-aldex2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

(base) [sbslee@grchead ~]$
```

BTW, it's certainly interesting that you, as a Mac OS user, cannot reproduce the issue. Which version of Mac OS are you using? I'm currently using Catalina (version 10.15.7). I first suspected that it was my Mac that was giving me hard time, but the fact that I'm getting the same issue in Linux (i.e. our team's server) tells me it's something else. Maybe it's Anaconda issue (I'm using the latest version: Anaconda3-2020.11-Linux-x86_64). Can you kindly confirm you are using the latest Anaconda?

**Comment by sbslee** [comment]
P.S. @dgiguer, could you also take a look at my QIIME 2 forum [post](https://forum.qiime2.org/t/differential-abundance-analysis-e-g-ancom-for-paired-samples-e-g-normal-tissue-vs-tumor-tissue-from-cancer-patients/17649/7) when you get a chance? I'm interested in running `aldex.ttest` for paired samples (normal tissue vs. tumor tissue from cancer patients), but I'm not sure how to provide pair information to the function. I'm aware that I need to set `paired.test = TRUE`, but how does the function know which samples are from the same patient (i.e. paired)? Thanks.

**Comment by sbslee** [comment]
I'm sorry to bombard you with notifications, @dgiguer, BUT I SOLVED THE ISSUE! ALDEx2 installed without any issues when I configured my Anaconda as follows:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

I'm still not sure why this fixed my issue because I did specify the bioconda channel in my previous command `conda create -n aldex2 -c bioconda bioconductor-aldex2`, but I guess it doesn't matter anymore now that the issue has been resolved. It looks like the above configuration is almost essential when it comes to R package management via Anaconda, and I just didn't know about this (I'm new to the R + Anaconda combination). Anyways, thanks for your help and still looking forward to hearing your answer regarding `aldex.ttest`. Thanks!

**Comment by ggloor** [comment]
to run a paired t-test, the samples must be in order of pairing.

So A1,B1,A2,B2 etc or A1,A2,A3,... B1,B2,B3 ...

best
greg

**Comment by dgiguer** [comment]
> P.S. @dgiguer, could you also take a look at my QIIME 2 forum [post](https://forum.qiime2.org/t/differential-abundance-analysis-e-g-ancom-for-paired-samples-e-g-normal-tissue-vs-tumor-tissue-from-cancer-patients/17649/7) when you get a chance? I'm interested in running `aldex.ttest` for paired samples (normal tissue vs. tumor tissue from cancer patients), but I'm not sure how to provide pair information to the function. I'm aware that I need to set `paired.test = TRUE`, but how does the function know which samples are from the same patient (i.e. paired)? Thanks.

looks like this was answered in #35 !

**Comment by sbslee** [comment]
@dgiguer, yes indeed, thanks!
