### ISSUE TITLE
suspicious pattern in results

### ISSUE THREAD

**Issue by sformel** [ggloor/ALDEx_bioc#36]
_I'm not sure if there is a more appropriate place for this question, if so, could you please point me there?  And thank you in advance!_

I've gotten some very suspicious looking results from my data, I'm curious if you might be able to give any insight into what would be driving this "handprint" looking pattern? 

I'm not sure what the quasi-symmetry and/or each cluster on the plot might represent.  I see similar patterns in Fernandes et al. (Figure 4) but they aren't anywhere near as extreme.  I suspect they are indications of a poor model fit, but I don't understand the models well enough to be sure how to investigate further. 

All the results are from the same experiment, which had 3 replicates for each treatment.  All three followed fairly standard Illumina sequencing protocols and DADA2 or Trinity based workflows.

#### Soil 16S data

![16S auto1](https://user-images.githubusercontent.com/21973147/103951070-a4689080-5103-11eb-9fda-6b5269fc57d3.png)

#### Soil ITS data

![ITS auto1](https://user-images.githubusercontent.com/21973147/103951219-e396e180-5103-11eb-977a-556fc8b1c0a5.png)

#### Root Transcriptome

![auto1](https://user-images.githubusercontent.com/21973147/103951415-3ffa0100-5104-11eb-9f53-d72838febf90.png)

### Test

As a test, I've run the Aldex "selex" data and the phyloseq "Global Patterns" data.  The latter had similar patterns to my data, but not as extreme.  

#### Selex Data

![selex1](https://user-images.githubusercontent.com/21973147/103952067-594f7d00-5105-11eb-8b74-68749ab468b8.png)

#### Global Patterns Data (soil and sediment data)

![globalpatterns1](https://user-images.githubusercontent.com/21973147/103952385-f0b4d000-5105-11eb-8a30-015af8bd7153.png)

**Comment by ggloor** [comment]
Hi. this is a very interesting pattern but not unprecedented

It is caused by differential sparsity in individual samples. What you are seeing is the pattern of unique low count (or 0 count) features in each sample. This is what is giving the individual 'rays' in the effect plot.

**Comment by sformel** [comment]
Thanks you for the explanation!  That actually makes sense given my experimental treatments.

**Comment by ggloor** [comment]
it's only obvious if you have seen it a thousand times :-)
