### ISSUE TITLE
effect size for paired samples

### ISSUE THREAD

**Issue by pooranis** [ggloor/ALDEx_bioc#40]
First, thanks for this package, and your clear documentation.

Is the way that ALDEx2 computes the effect size appropriate for paired samples?  It seems only ``aldex.ttest`` accepts a paired parameter.  ``aldex.effect`` does not.  We have a study with data collected from the same subjects at 2 time points.  There is a lot of within group variation as the subjects vary a lot from each other.  However, we are more interested in how subjects change over time, so we use a paired test.   In "old school" statistics, with Welch's paired _t_-test, we would compute the effect size based on the variation of subject's changes  ( variation in &Delta; where &Delta; = _t2_ - _t1_ for each subject).  Is there a way to coax ALDEx2 into computing this kind of effect size?  I see you can get the individual sample medians from ``aldex.clr``, from which we can calculate something like Cohen's paired _d_ , but I was curious if we could use/adapt ALDEx2's methods, as it seems more robust.

**Comment by acmasche** [comment]
Dear @ggloor, 
thank you for the great tool! 
I am also curious whether `aldex.effect` can be used for paired samples.

**Comment by ggloor** [comment]
This is a good feature to add. I will see if I can massage the effect size calculation to take pairing into account. As it stands now, it would be difficult.

**Comment by ggloor** [comment]
done will be in the next release. The only issue is that confidence intervals for the effect size is not calculated currently. To test, check with the selex dataset. The confidence intervals for most of the features of large effect are significantly smaller because the paired dispersion is larger than the unpaired dispersion.
