### ISSUE TITLE
Subsetting / pairwise comparisons

### ISSUE THREAD

**Issue by elayton13** [ggloor/ALDEx_bioc#46]
Hello

I am looking to use ALDEx to analyse my picrust data. I have the map files and the picrust output file for all of my samples. Am I right in thinking that in order to do pairwise comparisons I just subset the columns of my picrust output (attached as p2EC)  to only include the two groups that I am interested in, and then create a vector called conds as in the vignette:

conds <- c(rep("NS", 7), rep("S", 7))
x.all <- aldex(selex.sub, conds, mc.samples=16, test="t", effect=TRUE,
     include.sample.summary=FALSE, denom="all", verbose=FALSE)

And that the conds need to be listed in the order of the columns in the picrust data file to enable pairwise comparison? Just wanted to also double check that there is no other pre-processing required of the picrust output data file.

Thank you
[run1_EC_data.tsv.gz](https://github.com/ggloor/ALDEx_bioc/files/8359858/run1_EC_data.tsv.gz)

**Comment by ggloor** [comment]
yes, if your data is (c1,e1,c2,e2 ... ) or (c1,c2,...,e1,e2...) then pairwise analysis should work.
