### ISSUE TITLE
Question regarding the significance of the results

### ISSUE THREAD

**Issue by vdijckthomas** [ggloor/ALDEx_bioc#56]
Dear all,

I recently performed an analysis on my dataset:
-  investigating soil bacterial communities (ASVs obtained via 16S Illumina-sequencing)
-  two different vegetation types [Sedum (5 habitats) vs biodiverse (6 habitats)], 
- each habitat samples 4 times (3-4 samples per moment)
This resulted in 173 samples, and 8976 ASVs.

I used the the aldex() function with two groups:
aldex2_outp <- ALDEx2::aldex(otu.tab_transp, 
                            phyloseq::sample_data(ps_meta)$Vegetation,
                            mc.samples=128,
                            test="t",
                            effect = TRUE, 
                            denom="all",
                            verbose=FALSE,
                            paired.test=FALSE)

I have some difficulties with interpreting the results. I have attached the obtained plots down below.
![plot_ALDEx2](https://github.com/ggloor/ALDEx_bioc/assets/129847132/35ea18f5-ca04-463e-a804-b896901f0693)

The plots show that 51 ASVs are statistically significant (red dots). 
To the best of my knowledge, it is advised to look at the effect size of the dots.
As can be seen in the effect plot (rightside) no ASV has an effect size larger than 1 (ratio between group variation/within group variation).
The within-group variation is larger than the between-group variation.

Can I conclude that no ASV is differentially expressed between both groups, and that the ASVs that are annotated as statistically significant are a consequence of the within-group variation of these ASVs?

Many thanks for your help,

Kind regards.

Thomas

**Comment by vdijckthomas** [comment]
Thank you for your fast reply!

Would you be so kind as to explain how I can find these 4 ASVs in my plot so I can have a look at the samples they are found in?

Regarding the compositional biplot;
Initially, I performed an NMDS [dissimilarity matrix: mean values of repeated rarefaction using avgdist()].
Group (Sedum vs biodiverse) dispersions were homegeneous and the permutational analysis of variance [adonis()] showed that both groups differed in composition, although only a slight fraction of the variation could be explained by this (Rsquared = 0.053). 
I just made a compositional biplot, indicating the same result?
![PCA_biplot](https://github.com/ggloor/ALDEx_bioc/assets/129847132/e5ea3e4d-7eae-4a77-9624-937afcd7e80c)
Or grouped per habitat:
![PCA_per_habitat](https://github.com/ggloor/ALDEx_bioc/assets/129847132/08ada4e2-5dc8-460d-a0d2-618fc09d8228)

Thank you!

**Comment by vdijckthomas** [comment]
Any insights?

**Comment by ggloor** [comment]
x.e <- aldex.effect(x)

rownames(x.e)[which(x.e$rab.all> 5 & x.e$diff.btw < -4)]

**Comment by vdijckthomas** [comment]
Thank you for your fast reply. These values (rab.all> 5 and diff.btw < -4) are arbitrary?
Running your script resulted in 3 ASVs. The number of samples (%) they are found in, per condition, is summarize below:

                   | ASV1 | ASV2 | ASV3
Biodiverse | 69,6  | 83,3   | 77,5
Sedum       | 28,8  | 31,5   | 20,5
